---
- name: install packages
  become: yes
  package:
    name: nginx

- name: compile nginx.conf
  become: yes
  notify: reload-nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: compile default vhost
  become: yes
  notify: reload-nginx
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default

- name: generate diffie-hellman parameters
  become: yes
  openssl_dhparam:
    path: /etc/ssl/dhparams.pem

- name: start and enable nginx
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes

- name: open firewall
  become: yes
  ufw:
    rule: allow
    name: "Nginx Full"
