---
- hosts: all
  name: gather facts from every host
  tasks: [ ]

- hosts: all
  roles:
    - no_snapd
    - ufw
    - acme_cert
    - node_exporter

- hosts: rtmp
  roles:
    - docker

- hosts: grafana
  roles:
    - grafana

- hosts: prometheus
  roles:
    - prometheus
