---
- name: newer prometheus deb pkgs
  become: yes
  apt:
    deb: "{{ item }}"
  loop: "{{ prometheus_prometheus_debs }}"

- name: compile prometheus confguration
  become: yes
  notify: restart-prometheus
  template:
    src: prometheus.yaml.j2
    dest: /etc/prometheus/prometheus.yml

- name: target directory for file_sd_configs
  become: yes
  file:
    state: directory
    path: /etc/prometheus/file_sd_configs
    owner: root
    group: root
    mode: 0755

- name: compile file_sd_configs
  become: yes
  # no reload needed, prometheus picks up changes via inotify
  template:
    src: "file_sd_config_{{ item }}.yaml.j2"
    dest: "/etc/prometheus/file_sd_configs/{{ item }}.ansible.yaml"
  loop:
    - node

- name: start and enable prometheus
  become: yes
  service:
    name: prometheus
    state: started
    enabled: yes
