---
galaxy_info:
  role_name: ufw
  author: Jan Koppe <post@jankoppe.de>
  description: Install and enable ufw
  company: CHAOSWEST TV
  min_ansible_version: 2.4
  platforms:
    - name: Debian
      versions:
        - sid
        - buster
        - jessie
    - name: Ubuntu
      versions:
        - eoan
        - bionic
        - xenial
  license: MIT
dependencies: []
