---
- name: docker signing key
  become: yes
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: docker repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable main"
    state: present
    update_cache: yes

- name: install package
  become: yes
  apt:
    name: docker-ce

- name: compile docker configuration
  become: yes
  notify: restart-docker
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644

- name: enable and start docker
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: download docker-compose binary from github releases
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    #checksum: "sha256:https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64.sha256"
    dest: /usr/local/bin/docker-compose
    validate_certs: yes
    owner: root
    group: root
    mode: 0755
