---
- name: install package
  become: yes
  apt:
    name:
      - docker.io
      - docker-compose

- name: compile docker configuration
  become: yes
  notify: restart-docker
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644

- name: enable and start docker
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: install python-docker library
  become: yes
  pip:
    name: docker
    state: present
